apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-lesson-5-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otus-lesson-5
  template:
    metadata:
      labels:
        app: otus-lesson-5
    spec:
      containers:
      - name: otus-lesson-5
        image: alexanderrodnin/otus-lesson-5:0.0.1
        ports:
        - containerPort: 8000